- name: Record failover state
  copy:
    content: "Failover initiated at {{ ansible_date_time.iso8601 }}"
    dest: "{{ failover_status_file }}"
    mode: '0644'

- name: Update active validator record
  copy:
    content: "backup"
    dest: "{{ active_validator_file }}"
    mode: '0644'

- name: Check Main Validator Accessibility
  wait_for:
    host: "{{ main_validator_ip }}"
    port: "{{ main_validator_ssh_port }}"
    timeout: 10
  register: main_validator_accessible
  ignore_errors: yes
  delegate_to: localhost

- name: Handle Delinquent State - Main Validator Available
  block:
    - name: Update Main Validator Identity
      shell: "bash -c 'source ~/.profile && agave-validator -l {{ main_validator_ledger_path }} set-identity {{ main_validator_keys_path }}/unstaked-identity.json && ln -sf {{ main_validator_keys_path }}/unstaked-identity.json {{ main_validator_keys_path }}/identity.json'"
      delegate_to: "{{ main_validator_ip }}"
      ignore_errors: yes
      vars:
        ansible_port: "{{ main_validator_ssh_port }}"
        ansible_ssh_private_key_file: "{{ main_validator_ssh_key }}"
        ansible_user: "{{ main_validator_user }}"

    - name: Get tower filename
      shell: "basename $(ls {{ main_validator_ledger_path }}/tower-1_9-*.bin)"
      register: tower_filename
      delegate_to: "{{ main_validator_ip }}"
      vars:
        ansible_port: "{{ main_validator_ssh_port }}"
        ansible_ssh_private_key_file: "{{ main_validator_ssh_key }}"
        ansible_user: "{{ main_validator_user }}"

    - name: Create temp directory
      file:
        path: "/tmp/tower-backup"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Sync Tower to Sentry first
      shell: >
        rsync -avz -e "ssh -p {{ main_validator_ssh_port }} -i {{ main_validator_ssh_key }}"
        root@{{ main_validator_ip }}:{{ main_validator_ledger_path }}/{{ tower_filename.stdout }}
        /tmp/tower-backup/
      delegate_to: localhost

    - name: Sync Tower from Sentry to Backup
      shell: >
        rsync -avz -e "ssh -p {{ backup_validator_ssh_port }} -i {{ backup_validator_ssh_key }} -o StrictHostKeyChecking=no"
        /tmp/tower-backup/{{ tower_filename.stdout }}
        root@{{ backup_validator_ip }}:{{ backup_validator_ledger_path }}/
      delegate_to: localhost

    - name: Cleanup temp directory
      file:
        path: "/tmp/tower-backup"
        state: absent
      delegate_to: localhost

    - name: Activate Backup Validator
      shell: "bash -c 'source ~/.profile && agave-validator -l {{ backup_validator_ledger_path }} set-identity --require-tower {{ backup_validator_keys_path }}/staked-identity.json && ln -sf {{ backup_validator_keys_path }}/staked-identity.json {{ backup_validator_keys_path }}/identity.json'"
      delegate_to: "{{ backup_validator_ip }}"
      vars:
        ansible_port: "{{ backup_validator_ssh_port }}"
        ansible_ssh_private_key_file: "{{ backup_validator_ssh_key }}"
        ansible_user: "{{ backup_validator_user }}"

- name: Handle Delinquent State - Main Validator Unavailable
  block:
    - name: Copy Backup Tower and Activate
      shell: |
        cp {{ backup_validator_tower_path }}/tower-1_9-*.bin {{ backup_validator_ledger_path }}
        agave-validator -l {{ backup_validator_ledger_path }} set-identity --require-tower {{ backup_validator_keys_path }}/staked-identity.json
        ln -sf {{ backup_validator_keys_path }}/staked-identity.json {{ backup_validator_keys_path }}/identity.json
      when: main_validator_accessible.failed == true
      delegate_to: "{{ backup_validator_ip }}"
      vars:
        ansible_port: "{{ backup_validator_ssh_port }}"
        ansible_ssh_private_key_file: "{{ backup_validator_ssh_key }}"
        ansible_user: "{{ backup_validator_user }}"
