all:
  children:
    validators:
      hosts:
        main_validator:
          ansible_host: "{{ main_validator_ip }}"
          ansible_user: "{{ main_validator_user }}"
          ansible_ssh_private_key_file: "{{ main_validator_ssh_key }}"
          ansible_port: "{{ main_validator_ssh_port }}"
        backup_validator:
          ansible_host: "{{ backup_validator_ip }}"
          ansible_user: "{{ backup_validator_user }}"
          ansible_ssh_private_key_file: "{{ backup_validator_ssh_key }}"
          ansible_port: "{{ backup_validator_ssh_port }}"