- name: Get validator delinquent status
  shell: >
    solana validators --output json |
    jq -r '.validators[] | select(.identityPubkey == "{{ main_validator_identity_key }}") | .delinquent'
  register: validator_delinquent_status
  delegate_to: localhost

- name: Parse validator status
  set_fact:
    validator_found: "{{ validator_delinquent_status.stdout | length > 0 }}"
    validator_check: "{{ validator_delinquent_status.stdout == 'true' }}"

- name: Set monitoring status facts
  set_fact:
    monitoring_status:
      timestamp: "{{ ansible_date_time.iso8601 }}"
      active_validator: "{{ active_validator }}"
      main_validator_ssh: "{{ 'OK' if not ssh_check_main.failed else 'FAIL' }}"
      backup_validator_ssh: "{{ 'OK' if not ssh_check_backup.failed else 'FAIL' }}"
      validator_found: "{{ validator_found }}"
      delinquent: "{{ validator_check if validator_found else true }}"

- name: Log monitoring status
  copy:
    content: |
      Timestamp: {{ monitoring_status.timestamp }}
      Active Validator: {{ monitoring_status.active_validator }}
      Main Validator SSH: {{ monitoring_status.main_validator_ssh }}
      Backup Validator SSH: {{ monitoring_status.backup_validator_ssh }}
      Validator Found in Network: {{ monitoring_status.validator_found }}
      Delinquent Status: {{ monitoring_status.delinquent }}
      Identity Key: {{ main_validator_identity_key }}
    dest: "{{ system_state_path }}/last_check.log"
    mode: '0644'

- name: Debug validator info
  debug:
    msg: |
      Validator Found: {{ validator_found }}
      Delinquent Status: {{ validator_check }}
  when: not validator_found
